package org.wang.bootdemo.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import org.wang.bootdemo.model.Product;

import java.util.List;

/**
 * 产品mapper类
 * @author wanghao
 */
@Repository
@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    /**
     * @description 根据产品代码查询产品信息
     * @author wangHao
     * @date 2020/1/5 17:50
     * @param [productCode]
     * @return org.wang.bootdemo.model.Product
     */
    List<Product> getProductByProductCode(String productCode);

    /**
     * @description 根据产品名称查询产品信息
     * @author wangHao
     * @date 2020/1/7 22:49
     * @param [productName]
     * @return java.util.List<org.wang.bootdemo.model.Product>
     */
    List<Product> getProductListByProductName(String productName);
}