package org.wang.bootdemo.model;

import org.springframework.stereotype.Component;
import org.wang.bootdemo.utils.DateHelper;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_product
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class Product implements Serializable {
    /**
     * Database Column Remarks:
     *   产品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   产品代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   产品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_price
     *
     * @mbg.generated
     */
    private Double productPrice;

    /**
     * Database Column Remarks:
     *   产品状态 0-下架1-上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_status
     *
     * @mbg.generated
     */
    private String productStatus;

    /**
     * Database Column Remarks:
     *   产品类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     * Database Column Remarks:
     *   产品图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_img
     *
     * @mbg.generated
     */
    private String productImg;

    /**
     * Database Column Remarks:
     *   产品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_desc
     *
     * @mbg.generated
     */
    private String productDesc;

    /**
     * Database Column Remarks:
     *   产品创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   产品更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_id
     *
     * @return the value of t_product.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_id
     *
     * @param productId the value for t_product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_code
     *
     * @return the value of t_product.product_code
     *
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_code
     *
     * @param productCode the value for t_product.product_code
     *
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_name
     *
     * @return the value of t_product.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_name
     *
     * @param productName the value for t_product.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_price
     *
     * @return the value of t_product.product_price
     *
     * @mbg.generated
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_price
     *
     * @param productPrice the value for t_product.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_status
     *
     * @return the value of t_product.product_status
     *
     * @mbg.generated
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_status
     *
     * @param productStatus the value for t_product.product_status
     *
     * @mbg.generated
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_type
     *
     * @return the value of t_product.product_type
     *
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_type
     *
     * @param productType the value for t_product.product_type
     *
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_img
     *
     * @return the value of t_product.product_img
     *
     * @mbg.generated
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_img
     *
     * @param productImg the value for t_product.product_img
     *
     * @mbg.generated
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_desc
     *
     * @return the value of t_product.product_desc
     *
     * @mbg.generated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_desc
     *
     * @param productDesc the value for t_product.product_desc
     *
     * @mbg.generated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_time
     *
     * @return the value of t_product.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        if(createTime == null){
            return  null;
        }else{
            return (Date) createTime.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_time
     *
     * @param createTime the value for t_product.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        if(createTime == null){
           this.createTime = null;
        }else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.update_time
     *
     * @return the value of t_product.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        if(updateTime == null){
            return null;
        }else {
            return (Date) updateTime.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.update_time
     *
     * @param updateTime the value for t_product.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        if(updateTime == null){
            this.updateTime = null;
        }else {
            this.updateTime = (Date) updateTime.clone();
        }
    }

    @Override
    public String toString(){
        String str = "productId=" + getProductId() + ",productCode=" + getProductCode() + ",productName=" + getProductName() +
                ",productPrice=" + getProductPrice() + ",productStatus=" + getProductStatus() +
                ",productType=" + getProductType() + ",productImg=" + getProductImg() +
                ",createTime=" + DateHelper.dateToString(getCreateTime(), "yyyy-mm-dd hh:mm:ss") +
                ",updateTime=" + DateHelper.dateToString(getUpdateTime(), "yyyy-mm-dd hh:mm:ss") +
                ",productDesc=" + getProductDesc();
        return str;
    }
}